# <center> **Data Wrangling** </center>

In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [5]:
df_falcon = pd.read_csv("/content/DbApi_bruto_falcon_09.csv")
df_falcon.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,NaN,LEO,CCSFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.0,LEO,CCSFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.0,ISS,CCSFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.0,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.0,GTO,CCSFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857

### Verificação de valores nulo/ausentes

In [6]:
df_falcon.isnull().sum()

FlightNumber       0
Date               0
BoosterVersion     0
PayloadMass        5
Orbit              0
LaunchSite         0
Outcome            0
Flights            0
GridFins           0
Reused             0
Legs               0
LandingPad        26
Block              0
ReusedCount        0
Serial             0
Longitude          0
Latitude           0
dtype: int64

Pode se observar em duas variaveis, uma com 5 campos com ausencia de valor e outra, com 26 campos com ausencia de valor.

Será iniciado com a variavel, ``PayloadMass``, calcula se a média da coluna e substituísse os valores nulos pela média.

In [7]:
# Calcular a média da variavel "PayloadMass"
mean = df_falcon['PayloadMass'].mean()

# Substitir os valores np.nan pela média
df_falcon['PayloadMass'] = df_falcon['PayloadMass'].fillna(mean)

Agora não deve ter valores ausentes no conjunto de dados, exceto em ``LandingPad``.

In [8]:
# Após tratamento dos valores nulos
df_falcon.isnull().sum()

FlightNumber       0
Date               0
BoosterVersion     0
PayloadMass        0
Orbit              0
LaunchSite         0
Outcome            0
Flights            0
GridFins           0
Reused             0
Legs               0
LandingPad        26
Block              0
ReusedCount        0
Serial             0
Longitude          0
Latitude           0
dtype: int64

In [9]:
df_falcon.to_csv('Db_bruto_SpaceX_falcon_09.csv',
                 index=False,
                 index_label=False)